### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai201-tsigankova#15]
https://drive.google.com/file/d/1JyDN82JcLyx0T7sfTc0DpPWHgLITt2Rg/view?usp=sharing

**Comment by Tsigankova** [comment]
Завдання 1
Потреба: температура навколишнього середовища.
Доступність: інформація про температуру передається у базу даних ПП за допомогою спеціального обладнення, тому користувач має можливість її переглянути у будь-який час.
Цінність: для того, щоб переглянути температуру навколишнього середовища, не потрібно нічого платити.
Актуальність: зміни температури актуальні кожного разу, коли науковець формує прогноз погоди.

Завдання 2
Перший прецедент дає користувачу можливість переглидати зміни показників обладнання та проводити дослідження, тим самим наближає його до досягенення мети, пов'язаної з температурою навколишнього середовища.
Другий прецедент надає можливість зареєструватися або авторизуватися, тим самим наближає користувача до досягенення мети, пов'язаної з науковою діяльністю.
Третій прецедент дає можливість користувачу, в моєму випадку офісному робітнику, отримувати технічні запитання та надавати на них відповіді, тим самим наближає його до досягенення мети, пов'язаної з професійному спілкуванні.

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
